### PR TITLE
Columns with white space

### PR DESCRIPTION
**Pull request by jacobshaw42**
Fixes issue #30 without having to change column  names

### CODE REVIEW

**Comment by sfirke** [comment]
This would be a huge addition.  I have a dataframe that is slow to write with Pandas and I want to use BCP -- but it has columns with white spaces in the names and it would break a lot downstream if I change those.  @yehoshuadimarsky could this be reviewed + merged?

**Comment by yehoshuadimarsky** [comment]
please fix the merge conflicts first

**Comment by sfirke** [comment]
@jacobshaw42 can you please address the merge conflicts that have developed?

**Comment by jacobshaw42** [comment]
@yehoshuadimarsky  @sfirke Merge conflict resolved

**Comment by yehoshuadimarsky** [comment]
Thank you for your contribution!

**Pull request merged**
