### PR TITLE
Suppress pandas FutureWarnings

### LINKED ISSUE #156: FutureWarning: DataFrame Applymap Depricated.
Getting the following warning having updated Pandas.

...venv\lib\site-packages\bcpandas\constants.py:68: FutureWarning: DataFrame.applymap has been deprecated. 
Use DataFrame.map instead.
if not df.applymap(lambda x: delim in x if isinstance(x, str) else False).any().any():

### PR DESCRIPTION
**Pull request by JPhillips92**
Fixes #156.

### CODE REVIEW

**Comment by yehoshuadimarsky** [comment]
Thanks, but the better solution would be to just replace `applymap` with `map`, do you want to do that instead?

**Comment by yehoshuadimarsky** [comment]
looks great thanks. but why are you also changing the minimum python version from 3.8 to 3.9?

**Comment by JPhillips92** [comment]
Sorry I meant to add a comment about that yesterday. I had to bump python because pandas.DataFrame.map is new for pandas v2.1 [ref](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.map.html#pandas-dataframe-map) and it requires python 3.9 or higher [ref](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.map.html#pandas-dataframe-map).

**Comment by yehoshuadimarsky** [comment]
Sorry but Python 3.8 is still not end-of-life, I don't think we can drop support for it by requiring Python 3.9+

**Comment by JPhillips92** [comment]
@yehoshuadimarsky That's fair enough. Since we can't use `map` yet, do you want me to roll this back to the initial 'Suppress pandas FutureWarning' fix or just close it?

**Comment by taslater** [comment]
> @yehoshuadimarsky That's fair enough. Since we can't use `map` yet, do you want me to roll this back to the initial 'Suppress pandas FutureWarning' fix or just close it?

I'm sorry, why can't `map` be used instead of `applymap`?

**Comment by gordthompson** [comment]
3.8 went EOL two weeks ago.

**Comment by yehoshuadimarsky** [comment]
Sorry this took so long, it took me a while to get all the versions of pandas numpy and python to work with each other, finally dropped support for python 3.8 and added 3.12+ here https://github.com/yehoshuadimarsky/bcpandas/pull/218.

I hope this unblocks you, feel free to update your PR now. Note, I recently changed the build system to use `uv` from `poetry`.

**Comment by yehoshuadimarsky** [comment]
Thanks! Appreciate the patience as well

**Comment by yehoshuadimarsky** [comment]
Blocked from publishing this to PyPI until I resolve this issue, apologies: https://github.com/yehoshuadimarsky/bcpandas/issues/219

**Pull request merged**
