### PR TITLE
Use highest available driver version by default

### PR DESCRIPTION
**Pull request by deschman**
When driver_version is not specified at the time of creation of SqlCreds, check pyodbc for drivers with name matching "SQL Server" and return the highest number found after "Driver" (the driver version) in the driver name. If driver_version is specified, that version will still try to be used.

### CODE REVIEW

**Comment by yehoshuadimarsky** [comment]
Good idea. But first format it with Black so it passes CI. And also, the code is hard to read, can you split it up for readability into several parts?

**Comment by deschman** [comment]
Thank you for the direction, @yehoshuadimarsky! This one is looking cleaner. Any additional thoughts?

**Comment by yehoshuadimarsky** [comment]
Thanks this is great. Can you please add a test for this? Let me know if you need me to show you how

**Comment by deschman** [comment]
Got a chance to look back at adding that test today. Would love to get this put in. Thanks again, @yehoshuadimarsky

**Comment by deschman** [comment]
Can't really wrap my head around the issues but I'll look at it more later

**Comment by yehoshuadimarsky** [comment]
One of the `hypothesis` tests started failing, nothing to do with your PR, I confirmed it by running it on the master branch here https://github.com/yehoshuadimarsky/bcpandas/actions/runs/2515805708. I'll take a look and try to fix it

**Pull request merged**
