### PR TITLE
Added dtype parameter to to_sql function for passing on to pandas' API

### PR DESCRIPTION
**Pull request by matthiasschuurmans**

### CODE REVIEW

**Comment by matthiasschuurmans** [comment]
@yehoshuadimarsky I don't think this PR is causing this unit test to fail, but I could be wrong, could you take a look and let me know if I need to adjust anything? Thanks!

**Comment by yehoshuadimarsky** [comment]
taking a look

**Comment by yehoshuadimarsky** [comment]
I think it was a mistake by upgrading versions of libraries, just reverted them, works on my machine now. Can you sync your branch from master? Github even just released a new button to do this on the web UI, but I can't do it in your repo because I don't have write permissions

image

**Comment by matthiasschuurmans** [comment]
@yehoshuadimarsky Done. Not sure how to trigger the checks though. First I pushed a merge-commit, figured that might not be desired, force-pushed a revert, rebased my local branch and force-pushed the rebase. But that's 7 hours ago now. Can you trigger the checks?

**Comment by yehoshuadimarsky** [comment]
I think it was an issue with Ubuntu being upgraded from 16.04 to 20.04, just pushed a fix to the CI, can you sync your branch from upstream master again and push it? Thanks

https://github.com/yehoshuadimarsky/bcpandas/commit/418604fbc68630909158b9f141f561a4b5b84ffc

**Comment by matthiasschuurmans** [comment]
@yehoshuadimarsky Done again. Third time's the charm?

**Comment by yehoshuadimarsky** [comment]
Can you please also add some tests for this features? Like checking that when dtype param is passed, the result is what was passed in, and when no param is passed, the result is the default?

**Comment by matthiasschuurmans** [comment]
@yehoshuadimarsky Done, though I used a real SqlServer instead of (I think) the docker container you have setup to run these tests, so I hope the tests also pass in that environment.

**Comment by yehoshuadimarsky** [comment]
Thanks! Actually your tests automatically _did_ use the docker container because they inherited from `_BaseToSql`, which automatically loads the pytest fixture named `database` which uses the docker container, so good work. I fixed up the tests to work, the params weren't working (pytest thinks they are fixtures, which don't exist with that name - other similar tests use the `hypothesis` decorator for those), and I think we are good to go. Thanks for your patience and bearing with me.

I should probably update the README with better instructions for contributing (setup conda env, how to write tests, etc)...

Just waiting for CI to finish now, then I'll merge it and publish a new version.

**Pull request merged**
